name: NodeJS with Grunt

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install
      
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install
        
    - name: Run Tests
      run: |
        cd backend
        npm test
        cd ../frontend
        npm test
